[uwsgi]
module = app:app

http = 0.0.0.0:5000
master = true
processes = 1
threads = 8
enable-threads = true
lazy-apps = true

need-app = true
die-on-term = true
vacuum = true
http-timeout = 604800
socket-timeout = 604800
